Repository hansung-MobileCapstone/PlantyNote, pull requests merged in 2024-12, with the labels that each got.

#50 [design] 내식물타임라인페이지 퍼블리싱
  lib/screens/community/post_detail_screen.dart
  lib/screens/modals/memo_create_modal.dart
  lib/screens/modals/notification_setting_modal.dart
  lib/screens/plants/my_plant_timeline_screen.dart
  lib/widgets/inputs/emoji_selector.dart
  lib/widgets/profile/change_password_modal.dart
Labels: ☘️ 서희, 🎨 Design

#58 [feat] 내식물등록페이지 기능 구현
  lib/screens/plants/my_plant_collection_screen.dart
  lib/screens/plants/my_plant_register_screen.dart
  lib/widgets/components/plant_list_item.dart
Labels: ☘️ 서희, 🚀 Feat

#60 [feat] 내식물타임라인페이지 기능 구현
  lib/routes/plants_routes.dart
  lib/screens/modals/memo_create_modal.dart
  lib/screens/modals/timeline_modal.dart
  lib/screens/plants/my_plant_register_screen.dart
  lib/screens/plants/my_plant_timeline_screen.dart
  lib/widgets/components/memo_item.dart
  lib/widgets/components/plant_list_item.dart
Labels: ☘️ 서희, 🚀 Feat

#56 [Feat] 마이 페이지 기능 구현
  assets/images/basic_profile.png
  lib/screens/auth/signup_screen.dart
  lib/screens/profile/my_page_edit_screen.dart
  lib/screens/profile/my_page_screen.dart
  lib/widgets/profile/change_password_modal.dart
Labels: 🎁 정곤, 🚀 Feat

#63 [feat] 게시물 등록 및 수정 구현
  firestore.rules
  lib/routes/community_routes.dart
  lib/screens/community/all_posts_screen.dart
  lib/screens/community/post_create_screen.dart
  lib/screens/community/post_detail_screen.dart
  lib/screens/modals/comment_modal.dart
  lib/widgets/components/comment_item.dart
  lib/widgets/components/post_item.dart
Labels: 🎶 동영, 🚀 Feat

#66 [fix] 게시물 오류 해결
  lib/widgets/components/post_item.dart
Labels: 🎶 동영, 🏷 Fix

#73 [fix] 게시물(전체, 상세) 페이지 정보 없음 부분 오류 해결
  lib/screens/community/all_posts_screen.dart
  lib/screens/community/post_create_screen.dart
  lib/screens/community/post_detail_screen.dart
  lib/widgets/components/post_item.dart
Labels: 🎶 동영, 🏷 Fix

#75 [fix] 사용자 닉네임, 프로필 보이기
  lib/screens/community/all_posts_screen.dart
  lib/screens/community/post_create_screen.dart
  lib/widgets/components/post_item.dart
Labels: ☘️ 서희, 🏷 Fix

#69 게시글과 firebase 연동 기능 구현
  lib/screens/main/main_screen.dart
  lib/screens/profile/my_page_edit_screen.dart
  lib/screens/profile/my_page_screen.dart
Labels: 🎁 정곤, 🚀 Feat

#71 [refactor] 댓글에 닉네임 추가
  lib/screens/modals/comment_modal.dart
  lib/widgets/components/comment_item.dart
Labels: ☘️ 서희, 🧹 Refactor

#64 [refactor] 입력창 포커싱 고정, 색상 변경
  lib/screens/auth/login_screen.dart
  lib/screens/auth/signup_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: 🐱‍👤 예진, 🧹 Refactor

#77 [Refactor] 메인페이지 오류 해결
  lib/screens/main/main_screen.dart
Labels: 🐱‍👤 예진, 🧹 Refactor
