Repository hansung-MobileCapstone/PlantyNote, pull requests merged in 2025-05, with the labels that each got.

#104 [feat] 지도 식물 등록페이지 구현
  ios/Podfile.lock
  ios/Runner/Info.plist
  lib/routes/map_routes.dart
  lib/screens/map/map_create_screen.dart
  lib/screens/map/map_screen.dart
  lib/screens/modals/location_modal.dart
  lib/util/addressAndLatLng.dart
  pubspec.lock
  pubspec.yaml
Labels: ☘️ 서희, 🚀 Feat

#105 [feat] 지도페이지 마커 추가
  assets/images/map_marker.png
  lib/screens/map/map_screen.dart
Labels: ☘️ 서희, 🚀 Feat

#110 [feat] 앱 로고, 이름 반영
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/100.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/1024.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/114.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/120.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/144.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/152.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/167.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/180.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/20.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/29.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/40.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/50.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/57.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/58.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/60.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/72.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/76.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/80.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/87.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/Runner/Info.plist
Labels: ☘️ 서희, 🚀 Feat

#109 [design][feat] 지도식물 상세페이지 퍼블리싱, 구현
  lib/routes/map_routes.dart
  lib/screens/map/map_create_screen.dart
  lib/screens/map/map_detail_screen.dart
  lib/screens/map/map_screen.dart
  lib/screens/modals/comment_modal.dart
  lib/screens/modals/location_modal.dart
  lib/util/dateFormat.dart
  lib/widgets/components/map_item.dart
Labels: ☘️ 서희, 🎨 Design, 🚀 Feat

#111 [fix] 게시물 관련 오류 수정
  lib/screens/community/post_create_screen.dart
  lib/screens/community/post_detail_screen.dart
  lib/screens/main/main_screen.dart
  lib/widgets/components/post_item.dart
Labels: ☘️ 서희, 🏷 Fix

#113 [fix] AndroidManifest.xml 오류 해결
  android/app/src/main/AndroidManifest.xml
  pubspec.lock
Labels: 🎶 동영, 🏷 Fix

#118 [feat] 식물 전문가 기능 추가
  .gitignore
  android/app/src/main/AndroidManifest.xml
  ios/Runner/Info.plist
  lib/routes/app_router.dart
  lib/routes/conversation_routes.dart
  lib/screens/conversation/conversation_screen.dart
  lib/screens/main/main_screen.dart
  lib/services/plant_expert_service.dart
  lib/widgets/components/plant_expert_banner.dart
  pubspec.lock
  pubspec.yaml
Labels: 🎶 동영, 🚀 Feat

#120 [design][fix] 최종 UI 수정 및 오류 해결
  ios/Podfile.lock
  ios/Runner/Info.plist
  lib/screens/auth/login_screen.dart
  lib/screens/auth/login_start_screen.dart
  lib/screens/auth/signup_screen.dart
  lib/screens/community/post_create_screen.dart
  lib/screens/community/post_detail_screen.dart
  lib/screens/conversation/conversation_screen.dart
  lib/screens/main/main_screen.dart
  lib/screens/map/map_create_screen.dart
  lib/screens/map/map_screen.dart
  lib/screens/modals/calendar_modal.dart
  lib/screens/modals/comment_modal.dart
  lib/screens/modals/cycle_setting_modal.dart
  lib/screens/modals/memo_create_modal.dart
  lib/screens/notifications/push_notifications_screen.dart
  lib/screens/onboarding/plant_onboarding_screen.dart
  lib/screens/plants/my_plant_collection_screen.dart
  lib/screens/plants/my_plant_register_screen.dart
  lib/screens/plants/my_plant_timeline_screen.dart
  lib/screens/profile/my_page_edit_screen.dart
  lib/screens/profile/my_page_screen.dart
  lib/screens/search/search_screen.dart
  lib/screens/search/search_screen_result.dart
  lib/widgets/components/ConfirmDialog.dart
  lib/widgets/components/memo_item.dart
  lib/widgets/components/plant_expert_banner.dart
  lib/widgets/components/plant_list_item.dart
  lib/widgets/components/post_item.dart
  lib/widgets/profile/change_password_modal.dart
  pubspec.lock
Labels: ☘️ 서희, 🎨 Design, 🏷 Fix
